/*  DO NOT EDIT THIS FILE.

    It has been auto-edited by fixincludes from:

	"/usr/local/te/tool/Linux-i686/arm_2-unknown-tkernel/sys-include/stddef.h"

    This had to be done to correct non-standard usages in the
    original, manufacturer supplied header file.  */

/*
 *	@(#)stddef.h 02-03-05
 *
 *	C 言語：共通定義
 *	Copyright (C) 2002 by Personal Media Corporation
 */

#ifndef __STDDEF_H__
#define __STDDEF_H__

#include "stdtype.h"

#ifdef __cplusplus
extern "C" {
#endif

#if !defined(_GCC_PTRDIFF_T)
#define _GCC_PTRDIFF_T
typedef __PTRDIFF_TYPE__ ptrdiff_t;
#endif


#ifdef	__size_t
#if !defined(_GCC_SIZE_T)
#define _GCC_SIZE_T
typedef __SIZE_TYPE__ size_t;
#endif

#undef	__size_t
#endif

#ifdef	__wchar_t
#if !defined(_GCC_WCHAR_T) && ! defined(__cplusplus)
#define _GCC_WCHAR_T
typedef __WCHAR_TYPE__ wchar_t;
#endif

#undef	__wchar_t
#endif

#define	offsetof(type, member)	( (size_t)(&((type *)0)->member) )
#define	NULL	0

#ifdef __cplusplus
}
#endif
#endif /* __STDDEF_H__ */
