/*  DO NOT EDIT THIS FILE.

    It has been auto-edited by fixincludes from:

	"/usr/local/te/tool/Linux-i686/arm_2-unknown-tkernel/sys-include/stdlib.h"

    This had to be done to correct non-standard usages in the
    original, manufacturer supplied header file.  */

/*
 *	@(#)stdlib.h 02-11-14
 *
 *	C 言語：一般ユーティリティー
 *	Copyright (C) 2002 by Personal Media Corporation
 *
 *	★印は、BTRON のプロセス環境用である。T-Kernel のみでは動作しない。
 *	印のないものは環境に依存せず使用できる。
 *	×印は、実装されていない。
 */

#ifndef	__STDLIB_H__
#define	__STDLIB_H__

#include "stdtype.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef	__size_t
#if !defined(_GCC_SIZE_T)
#define _GCC_SIZE_T
typedef __SIZE_TYPE__ size_t;
#endif

#undef	__size_t
#endif

#ifdef	__wchar_t
#if !defined(_GCC_WCHAR_T) && ! defined(__cplusplus)
#define _GCC_WCHAR_T
typedef __WCHAR_TYPE__ wchar_t;
#endif

#undef	__wchar_t
#endif

typedef	struct {
	int		quot, rem;
} div_t;

typedef	struct {
	long int	quot, rem;
} ldiv_t;

#define	NULL		0

#define	EXIT_SUCCESS	0
#define	EXIT_FAILURE	(-1)

#define	RAND_MAX	32767

#define	MB_CUR_MAX	__mb_cur_max

/* 文字列変換関数 */
extern double atof( const char *nptr );
extern int atoi( const char *nptr );
extern long int atol( const char *nptr );
extern double strtod( const char *nptr, char **endptr );
extern long int strtol( const char *nptr, char **endptr, int base );
extern unsigned long int strtoul( const char *nptr, char **endptr, int base );

/* 疑似乱数列生成関数 */
extern int rand( void );
extern void srand( unsigned int seed );

/* 記憶領域管理関数 */
extern void* malloc( size_t size );					/*★*/
extern void* calloc( size_t nmemb, size_t size );			/*★*/
extern void* realloc( void *ptr, size_t size );				/*★*/
extern void free( void *ptr );						/*★*/

/*
 * malloc テスト機能 (C 言語標準仕様外)
 *	mode = 0	通常モード
 *	mode = 1	デバッグモード
 *	mode = -1	使用状況ダンプ
 *	mode = -2	使用状況詳細ダンプ
 */
extern void malloctest( int mode );					/*★*/
extern int malloccheck( void *ptr );					/*★*/

/* 環境に関する関数 */
extern void abort( void );						/*★*/
extern int atexit( void (*func)( void ) );				/*★*/
extern void exit( int status );						/*★*/
extern char* getenv( const char *name );				/*×*/
extern int system( const char *string );				/*×*/

/* 探索・検索ユーティリティ */
extern void* bsearch( const void *key, const void *base,
			size_t nmemb, size_t size,
			int (*compar)( const void*, const void* ) );
extern void qsort( void *base, size_t nmemb, size_t size,
			int (*compar)( const void*, const void* ) );

/* 整数算術関数 */
extern int abs( int j );
extern long int labs( long int j );
extern div_t div( int numer, int denom );
extern ldiv_t ldiv( long int numer, long int denom );

/* 多バイト文字関数 */
extern int mblen( const char *s, size_t n );				/*×*/
extern int mbtowc( wchar_t *pwc, const char *s, size_t n );		/*×*/
extern int wctomb( char *s, wchar_t wchar );				/*×*/

/* 多バイト文字列関数 */
extern size_t mbstowcs( wchar_t *pwcs, const char *s, size_t n );	/*×*/
extern size_t wcstombs( char *s, const wchar_t *pwcs, size_t n );	/*×*/

#ifdef __cplusplus
}
#endif
#endif /* __STDLIB_H__ */
